# Generated by Django 3.2.7 on 2022-05-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicants',
            old_name='Relation',
            new_name='Relationship',
        ),
    ]
