# Generated by Django 3.2.7 on 2022-05-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='JobId',
            new_name='Id',
        ),
    ]
