# Generated by Django 3.2.7 on 2022-05-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicants',
        ),
    ]
