# Generated by Django 3.2.7 on 2022-05-10 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='Applicant_id',
            field=models.OneToOneField(default=34, on_delete=django.db.models.deletion.CASCADE, related_name='Applicant', to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicants',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
