# Generated by Django 3.2.7 on 2022-05-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220510_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='id',
        ),
        migrations.AlterField(
            model_name='applicants',
            name='Applicant_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
