# Generated by Django 3.2.7 on 2022-05-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_relation_applicants_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicants',
            old_name='Relationship',
            new_name='Rel',
        ),
    ]
