# Generated by Django 3.2.7 on 2022-05-10 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_applicants_relate'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='Relate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='user.userprofile'),
        ),
    ]
