# Generated by Django 3.2.7 on 2022-05-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_relationship_applicants_rel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='Rel',
        ),
        migrations.AddField(
            model_name='applicants',
            name='Relate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='user.userprofile'),
        ),
    ]
