# Generated by Django 3.2.7 on 2022-05-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_applicants_relate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Contact', models.IntegerField()),
                ('Availability', models.CharField(max_length=255)),
                ('Salary_Expectations', models.CharField(max_length=255)),
                ('Relate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply', to='user.userprofile')),
            ],
        ),
    ]
