# Generated by Django 3.2.7 on 2022-05-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_apply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicants',
        ),
    ]
