# Generated by Django 3.2.7 on 2022-05-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='Relate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply', to='user.userprofile'),
        ),
    ]
