# Generated by Django 3.2.7 on 2022-05-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_apply_relate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
